[build]
  base = "Wal-za/Senderismo"            # Cambia a "Senderismo" en lugar de "Alma-Montana"
  publish = "Senderismo"         # Si tu sitio está en ese directorio, usa el mismo nombre
  command = "npm run build"      # Comando para construir el sitio (ajusta si es necesario)

[build.environment]
  NODE_VERSION = "16"            # Puedes especificar la versión de Node.js que estás utilizando

[[redirects]]
  from = "/old-url"
  to = "/new-url"
  status = 301
